version: '3.8'

services:
  db:
    image: mariadb:10.5
    container_name: mariadb_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "9999:3306" 
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - app_network

  api:
    build: .
    container_name: node_api
    depends_on:
      - db
    environment:
      DB_HOST: db  
      DB_PORT: 3306
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "3000:3000"  
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
